import React from "react";
import { Link } from "react-router-dom";
import "./Home.css";

const Home = () => {
  const token = localStorage.getItem("token");

  return (
    <div className="home-container">
      <header className="hero-section">
        <div className="hero-badge">AI-Powered ATS Score Analysis</div>
        <h1>
          Land Your Dream Job with <br />
          <span className="gradient-text">Resume ATS Analysis</span>
        </h1>
        <p className="hero-subtitle">
          Upload your resume PDF, compare it against any job description, and get instant recommendations, keyword matching, and Google Gemini AI insights to beat the applicant tracking systems.
        </p>

        <div className="hero-ctas">
          {token ? (
            <Link to="/resumes" className="cta-primary">
              Go to Dashboard →
            </Link>
          ) : (
            <>
              <Link to="/register" className="cta-primary">
                Get Started Free
              </Link>
              <Link to="/login" className="cta-secondary">
                Sign In
              </Link>
            </>
          )}
        </div>
      </header>

      <section className="features-grid">
        <div className="feature-card">
          <div className="feature-icon">📊</div>
          <h3>Compatibility Scoring</h3>
          <p>Instantly calculate what percentage of keywords in the job description appear on your resume.</p>
        </div>
        <div className="feature-card">
          <div className="feature-icon">🔍</div>
          <h3>Skill Gap Detection</h3>
          <p>Find which programming languages, frameworks, or general skills are missing compared to the JD.</p>
        </div>
        <div className="feature-card">
          <div className="feature-icon">💡</div>
          <h3>Gemini AI Suggestions</h3>
          <p>Receive detailed, bullet-by-bullet improvement tips and phrasing modifications generated by advanced AI.</p>
        </div>
      </section>
    </div>
  );
};

export default Home;
